// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { problemsCreateProblemData, problemsCreateProblemErrors, problemsCreateProblemResponses, problemsDeleteProblemData, problemsDeleteProblemErrors, problemsDeleteProblemResponses, problemsReadProblemData, problemsReadProblemErrors, problemsReadProblemResponses, problemsReadProblemsData, problemsReadProblemsResponses, problemsUpdateProblemData, problemsUpdateProblemErrors, problemsUpdateProblemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ProblemsService {
    /**
     * Read Problems
     *
     * Retrieve problems.
     */
    public static readProblems<ThrowOnError extends boolean = true>(options?: Options<problemsReadProblemsData, ThrowOnError>) {
        return (options?.client ?? client).get<problemsReadProblemsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/problems/',
            ...options
        });
    }
    
    /**
     * Create Problem
     *
     * Create new problem.
     */
    public static createProblem<ThrowOnError extends boolean = true>(options: Options<problemsCreateProblemData, ThrowOnError>) {
        return (options.client ?? client).post<problemsCreateProblemResponses, problemsCreateProblemErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/problems/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Problem
     *
     * Delete an item.
     */
    public static deleteProblem<ThrowOnError extends boolean = true>(options: Options<problemsDeleteProblemData, ThrowOnError>) {
        return (options.client ?? client).delete<problemsDeleteProblemResponses, problemsDeleteProblemErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/problems/{id}',
            ...options
        });
    }
    
    /**
     * Read Problem
     *
     * Get problem by ID.
     */
    public static readProblem<ThrowOnError extends boolean = true>(options: Options<problemsReadProblemData, ThrowOnError>) {
        return (options.client ?? client).get<problemsReadProblemResponses, problemsReadProblemErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/problems/{id}',
            ...options
        });
    }
    
    /**
     * Update Problem
     *
     * Update a problem.
     */
    public static updateProblem<ThrowOnError extends boolean = true>(options: Options<problemsUpdateProblemData, ThrowOnError>) {
        return (options.client ?? client).put<problemsUpdateProblemResponses, problemsUpdateProblemErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/problems/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
