// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * ProblemCreate
 */
export type ProblemCreate = {
    /**
     * Title
     */
    title: string;
    platform: ProblemPlatform;
    /**
     * Url
     */
    url: string;
    /**
     * Problem Id
     */
    problem_id?: string | null;
    difficulty: ProblemDifficulty;
    /**
     * Normalized Difficulty
     */
    normalized_difficulty?: number | null;
    /**
     * Simplified Statement
     */
    simplified_statement?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Solution Url
     */
    solution_url?: string | null;
};

/**
 * ProblemDifficulty
 */
export type ProblemDifficulty = 'easy' | 'medium' | 'hard';

/**
 * ProblemPlatform
 */
export type ProblemPlatform = 'leetcode' | 'hackerrank';

/**
 * ProblemPublic
 */
export type ProblemPublic = {
    /**
     * Title
     */
    title: string;
    platform: ProblemPlatform;
    /**
     * Url
     */
    url: string;
    /**
     * Problem Id
     */
    problem_id?: string | null;
    difficulty: ProblemDifficulty;
    /**
     * Normalized Difficulty
     */
    normalized_difficulty?: number | null;
    /**
     * Simplified Statement
     */
    simplified_statement?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Solution Url
     */
    solution_url?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProblemUpdate
 */
export type ProblemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    platform?: ProblemPlatform | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Problem Id
     */
    problem_id?: string | null;
    difficulty?: ProblemDifficulty | null;
    /**
     * Normalized Difficulty
     */
    normalized_difficulty?: number | null;
    /**
     * Simplified Statement
     */
    simplified_statement?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Solution Url
     */
    solution_url?: string | null;
};

/**
 * ProblemsPublic
 */
export type ProblemsPublic = {
    /**
     * Data
     */
    data: Array<ProblemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type problemsReadProblemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/problems/';
};

export type problemsReadProblemsResponses = {
    /**
     * Successful Response
     */
    200: ProblemsPublic;
};

export type problemsReadProblemsResponse = problemsReadProblemsResponses[keyof problemsReadProblemsResponses];

export type problemsCreateProblemData = {
    body: ProblemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/problems/';
};

export type problemsCreateProblemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type problemsCreateProblemError = problemsCreateProblemErrors[keyof problemsCreateProblemErrors];

export type problemsCreateProblemResponses = {
    /**
     * Successful Response
     */
    200: ProblemPublic;
};

export type problemsCreateProblemResponse = problemsCreateProblemResponses[keyof problemsCreateProblemResponses];

export type problemsDeleteProblemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/problems/{id}';
};

export type problemsDeleteProblemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type problemsDeleteProblemError = problemsDeleteProblemErrors[keyof problemsDeleteProblemErrors];

export type problemsDeleteProblemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type problemsDeleteProblemResponse = problemsDeleteProblemResponses[keyof problemsDeleteProblemResponses];

export type problemsReadProblemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/problems/{id}';
};

export type problemsReadProblemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type problemsReadProblemError = problemsReadProblemErrors[keyof problemsReadProblemErrors];

export type problemsReadProblemResponses = {
    /**
     * Successful Response
     */
    200: ProblemPublic;
};

export type problemsReadProblemResponse = problemsReadProblemResponses[keyof problemsReadProblemResponses];

export type problemsUpdateProblemData = {
    body: ProblemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/problems/{id}';
};

export type problemsUpdateProblemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type problemsUpdateProblemError = problemsUpdateProblemErrors[keyof problemsUpdateProblemErrors];

export type problemsUpdateProblemResponses = {
    /**
     * Successful Response
     */
    200: ProblemPublic;
};

export type problemsUpdateProblemResponse = problemsUpdateProblemResponses[keyof problemsUpdateProblemResponses];
