"""initialize problem model

Revision ID: bbd7ea20863f
Revises:
Create Date: 2026-09-01 21:12:48.565333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbd7ea20863f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('platform', sa.Enum('leetcode', 'hackerrank', name='problemplatform'), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('problem_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='problemdifficulty'), nullable=False),
    sa.Column('normalized_difficulty', sa.Integer(), nullable=True),
    sa.Column('simplified_statement', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('solution_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('normalized_difficulty IS NULL OR normalized_difficulty BETWEEN 1 AND 10', name='ck_problem_normalized_difficulty_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'problem_id', name='uq_problem_platform_problem_id')
    )
    op.create_index(op.f('ix_problem_difficulty'), 'problem', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problem_normalized_difficulty'), 'problem', ['normalized_difficulty'], unique=False)
    op.create_index(op.f('ix_problem_platform'), 'problem', ['platform'], unique=False)
    op.create_index('ix_problem_platform_difficulty', 'problem', ['platform', 'difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problem_platform_difficulty', table_name='problem')
    op.drop_index(op.f('ix_problem_platform'), table_name='problem')
    op.drop_index(op.f('ix_problem_normalized_difficulty'), table_name='problem')
    op.drop_index(op.f('ix_problem_difficulty'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
